eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.111:8888/eureka/
instance:
       instance-id:
       prefer-ip-address: true
server:
  port: 8763
spring:
  application:
    name: service-member
