eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.104:8888/eureka/
instance:
       instance-id:
       prefer-ip-address: true
server:
  port: 8762
spring:
  application:
    name: service-user
  datasource:
    url: jdbc:mysql://localhost:3306/db_user?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true